In [25]:
import numpy as np
A = np.array([[1, 5, 3, 2], [1/5, 1, 1/2, 1/3], [1/3, 2, 1, 1/2], [1/2, 3, 2, 1]])
print(A.shape) #获取行，与列。或者用np.shape(array[])调用
n=A.shape[0]

(4, 4)


In [26]:
eig_val, eig_vec = np.linalg.eig(A) #获取特征值与特征向量
print(max(eig_val))
print(eig_vec)

(4.014520958632267+0j)
[[ 0.82867243+0.j         -0.91302225+0.j          0.77452999+0.j
   0.77452999-0.j        ]
 [ 0.15127294+0.j          0.16033653+0.j          0.03714621-0.1321065j
   0.03714621+0.1321065j ]
 [ 0.26940784+0.j         -0.17900827+0.j         -0.2947741 -0.07483972j
  -0.2947741 +0.07483972j]
 [ 0.4667311 +0.j          0.32960372+0.j         -0.03848152+0.53600163j
  -0.03848152-0.53600163j]]


In [27]:
max_eig_val = max(eig_val)
CI = (max_eig_val-n)/(n-1)
print(CI)
RI = {1:0.00, 2:0.0001, 3:0.52, 4:0.89, 5:1.12,6:1.26, 7:1.36, 8:1.41, 9:1.46, 10:1.49,
      11:1.52, 12:1.54, 13:1.56, 14:1.58, 15:1.59}

CR = CI/RI[n]
print(CR)
# then compare CR with 0.10.

(0.004840319544088996+0j)
(0.005438561285493255+0j)


In [ ]:
#算数平均法
A_col_sum = np.sum(A, axis=0) #axis=0,按列求和
print(A_col_sum)
#归一化
stand_A = A / A_col_sum
print(stand_A)
#在内存中，A_col_sum 相当于被瞬间“复制拉伸”成了这样, 再逐个相除
#[ 2.03333333 11.  6.5  3.83333333]
#[ 2.03333333 11.  6.5  3.83333333]
#[ 2.03333333 11.  6.5  3.83333333]
#[ 2.03333333 11.  6.5  3.83333333]
weight = np.sum(stand_A, axis=1)/n
print(weight)

[ 2.03333333 11.          6.5         3.83333333]
[[0.49180328 0.45454545 0.46153846 0.52173913]
 [0.09836066 0.09090909 0.07692308 0.08695652]
 [0.16393443 0.18181818 0.15384615 0.13043478]
 [0.24590164 0.27272727 0.30769231 0.26086957]]
[0.48240658 0.08828734 0.15750839 0.2717977 ]


In [36]:
#几何平均法
A_line_prod = np.prod(A, axis=1) #按行累×
print(A_line_prod)

A_line_prod_ = np.power(A_line_prod, 1/n)
weight = A_line_prod_ / np.sum(A_line_prod_)
print(weight)

[30.          0.03333333  0.33333333  3.        ]
[0.48318903 0.08821784 0.15687597 0.27171716]


In [49]:
#特征值法
eig_val, eig_vec = np.linalg.eig(A) #获取特征值与特征向量
eig_max = max(eig_val)
max_idx = np.argmax(eig_val) #获取最大值索引
print(eig_vec.T[max_idx]) #列向量转置用行索引
weight = eig_vec.T[max_idx] / np.sum(eig_vec.T[max_idx])
print(weight)
print(type(weight[0]))

[0.82867243+0.j 0.15127294+0.j 0.26940784+0.j 0.4667311 +0.j]
[0.48288562+0.j 0.08815006+0.j 0.15698986+0.j 0.27197446+0.j]
<class 'numpy.complex128'>
