In [44]:
import numpy as np
A = np.array([[90,4,35,15],[85,3,50,21],[92,4.5,40,19],[88,3.5,38,17]])
n, m = A.shape

In [45]:
#极小型指标正向化
_A = A.copy().T #在新的array操作
# 正向化
mx = np.max(_A[1])
_A[1] = mx-_A[1]
print(_A)

[[90.  85.  92.  88. ]
 [ 0.5  1.5  0.   1. ]
 [35.  50.  40.  38. ]
 [15.  21.  19.  17. ]]


In [46]:
#中间型指标正向化
best = 40 
__A = _A.copy()
__A[2] = np.abs(__A[2]-40)
mx = np.max(__A[2])
_A[2] = 1 - np.abs(_A[2]-40)/mx
print(_A)

[[90.  85.  92.  88. ]
 [ 0.5  1.5  0.   1. ]
 [ 0.5  0.   1.   0.8]
 [15.  21.  19.  17. ]]


In [47]:
#区间型正向化 16-18 best
a = 16; b = 18
mx = max(a-np.min(_A[3]), np.max(_A[3])-b)
print(mx)
for i in range(n):
    if _A[3][i] < a:
        _A[3][i] = 1-(a-_A[3][i]) / mx
    elif _A[3][i] <= b:
        _A[3][i] = 1
    else:
        _A[3][i] = 1-(_A[3][i]-b) / mx
print(_A)

3.0
[[90.         85.         92.         88.        ]
 [ 0.5         1.5         0.          1.        ]
 [ 0.5         0.          1.          0.8       ]
 [ 0.66666667  0.          0.66666667  1.        ]]


In [48]:
#归一化
A = _A.copy().T
print(A)
Aby = A.copy()*A.copy()
sm = np.sum(Aby, axis=0)

sm = np.sqrt(sm)
A = A/sm
print(A)

[[90.          0.5         0.5         0.66666667]
 [85.          1.5         0.          0.        ]
 [92.          0.          1.          0.66666667]
 [88.          1.          0.8         1.        ]]
[[0.50682714 0.26726124 0.36369648 0.48507125]
 [0.47867008 0.80178373 0.         0.        ]
 [0.51808997 0.         0.72739297 0.48507125]
 [0.49556432 0.53452248 0.58191437 0.72760688]]


In [ ]:
Z_best = np.max(A, axis=0) #np.array([np.max(A.T[i]) for i in range(m)])
Z_bad = np.min(A, axis=0)
score = np.zeros(shape=(4,1)) #创建零矩阵
w = 1/m #权重
D_best = A.copy()
D_bad = A.copy()

#calculate
D_best = w * np.power((A-Z_best), 2)
D_best = np.power(np.sum(D_best, axis=1), 0.5)
print(D_best)

D_bad = w * np.power((A-Z_bad), 2)
D_bad = np.power(np.sum(D_bad, axis=1), 0.5)
print(D_bad)

score = D_bad/(D_best+D_bad)
print(score)

[0.34530414 0.51479759 0.41883191 0.15256146]
[0.33158356 0.40089186 0.43759244 0.53713029]
[0.48986495 0.4378033  0.51095282 0.77879761]
