In [47]:
#这里使用Topsis法中，已经正向化，标准化的数据
import numpy as np
A = np.array([[0.50682714, 0.26726124, 0.36369648, 0.48507125],
[0.47867008, 0.80178373, 0.        , 0.        ],
 [0.51808997, 0.         ,0.72739297 ,0.48507125],
 [0.49556432, 0.53452248, 0.58191437 ,0.72760688]])
print(A)
n = A.shape[0]

[[0.50682714 0.26726124 0.36369648 0.48507125]
 [0.47867008 0.80178373 0.         0.        ]
 [0.51808997 0.         0.72739297 0.48507125]
 [0.49556432 0.53452248 0.58191437 0.72760688]]


In [48]:
#归一化
sm = np.sum(A, axis=0)
A = A/sm
print(A)

[[0.25352113 0.16666667 0.2173913  0.28571428]
 [0.23943662 0.5        0.         0.        ]
 [0.25915493 0.         0.43478261 0.28571428]
 [0.24788732 0.33333333 0.34782609 0.42857143]]


In [ ]:
A = (-1) * A * np.log(A, out=np.zeros_like(A), where= A>0) * 1/(np.log(n))
# np.zeros_like(A) 的参数就是一个参考数组，
# NumPy 会根据它创建一个形状（shape）和数据类型（dtype）相同、元素全为 0 的新数组。
print(A)
Dj = np.sum(A,axis=0)
Wj = 1-Dj
Wj = Wj/np.sum(Wj)
print(Wj)

[[ 0.25096337  0.21541354  0.23930803  0.25819356]
 [ 0.24689319  0.25       -0.         -0.        ]
 [ 0.25243158 -0.          0.26122475  0.25819356]
 [ 0.24940484  0.26416042  0.2649673   0.26194123]]
[0.00042238 0.3720241  0.32260067 0.30495286]
