In [18]:
import numpy as np

# 定义参数
# 因素集 U: 例如 [服务态度, 菜品质量, 环境卫生, 价格合理性]
factors = ['服务态度', '菜品质量', '环境卫生', '价格合理性']
n = len(factors)

# 评语集 V: 例如 [优, 良, 中, 差]
comments = ['优', '良', '中', '差']
m = len(comments)

# 权重向量 A (需满足归一化，和为1)
# 对应上述4个因素的权重
A = np.array([0.3, 0.3, 0.2, 0.2]) 
print(A)

[0.3 0.3 0.2 0.2]


In [19]:
# 构建模糊评价矩阵 R (n x m)

# R[i][j] 表示第i个因素被评为第j个等级的隶属度(概率)
# 数据通常来自问卷调查统计(如: 30人投票，15人选优，则隶属度为0.5)，或进行指派，理同正向化操作
R = np.array([
    [0.4, 0.3, 0.2, 0.1],  # 服务态度: 40%优, 30%良...
    [0.3, 0.4, 0.2, 0.1],  # 菜品质量
    [0.2, 0.3, 0.4, 0.1],  # 环境卫生
    [0.1, 0.2, 0.5, 0.2]   # 价格合理性
])

print("=== 模糊评价矩阵 R ===")
print(R)


=== 模糊评价矩阵 R ===
[[0.4 0.3 0.2 0.1]
 [0.3 0.4 0.2 0.1]
 [0.2 0.3 0.4 0.1]
 [0.1 0.2 0.5 0.2]]


In [20]:

# 模糊合成 B = A ∘ R

# 常用模型: M(∧,∨) 取小取大模型 或 M(·,+) 乘加模型(加权平均)
# 这里使用最常用的加权平均模型(矩阵乘法)，保留更多信息
B = A@R

print("\n=== 综合评价结果向量 B ===")
print(B)
print(f"验证归一化: sum(B) = {np.sum(B):.4f}")


=== 综合评价结果向量 B ===
[0.27 0.31 0.3  0.12]
验证归一化: sum(B) = 1.0000


In [21]:

# 结果判定

# 方法1: 最大隶属度原则
best_idx = np.argmax(B)
print(f"\n【最大隶属度原则】评价结果为: {comments[best_idx]} (隶属度={B[best_idx]:.4f})")

# 方法2: 加权评分法 (更精细)
# 假设评语集对应的分数为 [90, 80, 70, 60]
scores = np.array([90, 80, 70, 60])
final_score = np.dot(B, scores)
print(f"【加权评分法】综合得分: {final_score:.2f}")


【最大隶属度原则】评价结果为: 良 (隶属度=0.3100)
【加权评分法】综合得分: 77.30
