In [28]:
import numpy as np
A = np.array([[80,70,85,75,],[70,65,78,80],[90,75,80,85],[75,60,70,80]])
print(A)

[[80 70 85 75]
 [70 65 78 80]
 [90 75 80 85]
 [75 60 70 80]]


In [29]:
#已经正向化，直接统一量纲
mean = np.mean(A, axis=0)
print(mean)
A = A / mean
print(A)

[78.75 67.5  78.25 80.  ]
[[1.01587302 1.03703704 1.08626198 0.9375    ]
 [0.88888889 0.96296296 0.99680511 1.        ]
 [1.14285714 1.11111111 1.02236422 1.0625    ]
 [0.95238095 0.88888889 0.89456869 1.        ]]


In [30]:
#母序列
mother_array = np.max(A, axis=0)
print(mother_array)
A = np.abs(mother_array - A)
print(A)

[1.14285714 1.11111111 1.08626198 1.0625    ]
[[0.12698413 0.07407407 0.         0.125     ]
 [0.25396825 0.14814815 0.08945687 0.0625    ]
 [0.         0.         0.06389776 0.        ]
 [0.19047619 0.22222222 0.19169329 0.0625    ]]


In [31]:
# 参数们
rho = 0.5
a = np.min(np.min(A,axis=0))
b = np.max(np.max(A,axis=0))
print(a, b)

0.0 0.25396825396825395


In [32]:
A = (a + rho*b) / (A + rho*b)
print(A)
ans = np.mean(A, axis=1)
print(ans)

[[0.5        0.63157895 1.         0.50393701]
 [0.33333333 0.46153846 0.58669166 0.67015707]
 [1.         1.         0.66524973 1.        ]
 [0.4        0.36363636 0.39847231 0.67015707]]
[0.65887899 0.51293013 0.91631243 0.45806644]
